init:
  - git config --global core.autocrlf true
install:
  - npm install -g npm bower gulp
  - npm install
  - bower install
build_script:
  - build.cmd --quiet verify
clone_depth: 1
test: off
deploy: off
